name: Deploy to EKS

on:
  repository_dispatch:
    types: [deploy_to_eks]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the IaC repository
      uses: actions/checkout@v3

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v1
      with:
        version: '1.24.0'

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get EKS Cluster Credentials
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        if [ "${{ github.event.client_payload.repo }}" == "nodejs-server" ]; then
          echo "Deploying Node.js server..."
          LATEST_IMAGE=$(aws ecr describe-images --repository-name nodejs-server --query 'images | sort_by(@, &imagePushedAt) | [-1].imageTags[0]' --output text)
          kubectl apply -f kubernetes/deployment-nodejs.yaml
        elif [ "${{ github.event.client_payload.repo }}" == "nextjs-server" ]; then
          echo "Deploying Next.js server..."
          LATEST_IMAGE=$(aws ecr describe-images --repository-name nextjs-server --query 'images | sort_by(@, &imagePushedAt) | [-1].imageTags[0]' --output text)
          kubectl apply -f kubernetes/deployment-nextjs.yaml
        else
          echo "No valid repo specified. Exiting..."
          exit 1
        fi